### ISSUE TITLE
100% height doesn't work within a flex item in a flex-item child (Chrome / Safari)

### ISSUE THREAD

**Issue by somombo** [philipwalton/flexbugs#197]
I am posting this issue here because I haven't been able to find a workaround. 

In addition, this is a known issue in chrome and safari but appears to not have been listen on the flexbugs list (unless I'm mistaken). For more info, See https://bugs.webkit.org/show_bug.cgi?id=137730

Here is some code to reproduce the problem in Chrom and Safari (taken from http://jsfiddle.net/mLkp7L1j/2/) 

```html
<div class="flex">
    <div class="flex-item">
        <div class="element">
            The orange element should be as tall as the blue element
        </div>
    </div>
</div>
```
```css
.flex {
    height: 100px;
    display: -webkit-flex;
    display: flex;
    -webkit-flex-flow: column;
    flex-flow: column;
}
.flex-item {
    background-color: steelblue;
    -webkit-flex: 1 1 auto;
    flex: 1 1 auto;
}
.element {
    height: 100%;
    background-color: orange;
}
```

**Comment by philipwalton** [comment]
Do you have a workaround? Flexbugs only lists bugs in the README with known workarounds.

**Comment by mkurz** [comment]
https://bugs.webkit.org/show_bug.cgi?id=137730 has been marked as fixed now.

Can you share a chrome bug url?

**Comment by mkurz** [comment]
Also it looks like the jsfiddle is buggy:

> Note we do "fail" the jsfiddle but pass the mozilla test now. I think the jsfiddle is wrong, and that our behavior is correct according to the spec. I kind of think the spec is wrong here though. Anyway, we should match Chrome now.

(Taken from the webkit issue)

**Comment by gsnedders** [comment]
As @mkurz posted, the jsfiddle is wrong. Firefox and Edge break the spec in this case and are actually wrong as they don't implement:

>  If a flex item has a definite flex basis and the flex container has a definite main size, its post-flexing main size is treated as definite (even though it might technically rely on the sizes of indefinite siblings to resolve its flexed main size). 

Vitally, the jsfiddle has a flex-basis of `auto` which isn't definite in this case (as `height: auto` hence it falls back to behaving like `flex-basis: content` which is always indefinite). If you change to `flex: 1 1 0`, it works fine cross-browser (in this admittedly relatively simple case).

**Comment by somombo** [comment]
@philipwalton, as  @gsnedders has mentioned, it appears workaround seems to be to set basis to 0
I have tried this in opera, chrome. However, I dont have a machine with safari though. Perhaps someone can confirm that that works in safari?

**Comment by GoldenRust** [comment]
As previously mentioned, I believe this is the intended behaviour. Changing the `flex-basis` to `0` will give you your desired outcome in chrome. However, this still does not work in Safari. (Tested in 10.0.3)
[http://jsfiddle.net/mLkp7L1j/125/](http://jsfiddle.net/mLkp7L1j/125/)

Are there any suggested workarounds for Safari?

**Comment by mkurz** [comment]
@GoldenRust Safari 10.1 [was released yesterday](https://webkit.org/blog/7477/new-web-features-in-safari-10-1/). Can you update an try again?

**Comment by GoldenRust** [comment]
@mkurz I'll try later tonight when I have access to a mac, right now I'm limited to what Browser Stack can provide.

**Comment by gsnedders** [comment]
@mkurz No, it doesn't.

**Comment by mkurz** [comment]
@gsnedders Which test page did you try?

**Comment by gsnedders** [comment]
@mkurz the one linked by @GoldenRust, which is right per spec and passes in Nightly; the one linked by @somombo in the original post equally fails, but that's expected to fail and similarly does in Nightly.

**Comment by mkurz** [comment]
With Nightly you mean Safari technology preview? And you did test with Safari 10.1 (released yesterday)?

**Comment by gsnedders** [comment]
With Nightly I mean [Nightly](https://nightly.webkit.org), though yes, it also passes in Technology Preview. And yes, I did test with Safari 10.1.

**Comment by mkurz** [comment]
@gsnedders Seems we have to wait another couple of months before this hits stable :cry: Thanks for testing!

**Comment by jonas8** [comment]
I have this problem, the latest 10.1 safari doesn't fix this. My workaround is :
make the flex-item element as flexbox.

**Comment by GoldenRust** [comment]
@jonas8 I believe this works when the flex direction is set as `column`, but if it's set as row it doesn't.

**Comment by jonas8** [comment]
@GoldenRust It works as well when set as row.
`flex-direction: row`: http://jsfiddle.net/jonas8/ox2d2w4w/2/
`flex-direction: column`: http://jsfiddle.net/jonas8/w5jwxoL5/3/

**Comment by GoldenRust** [comment]
@jonas8 So it does! I forgot to add the `flex` attribute to the `.element`.

Thank you!

**Comment by philipwalton** [comment]
I don't think there is a generalized workaround for this, and in the interest of not having too many opened issues lingering, I'm going to close this one. If someone discovers a workaround, please feel free to open a new issue.

**Comment by dongepulango** [comment]
Thanks @jonas8

**Comment by dioogbento** [comment]
Thank you @jonas8

**Comment by everdimension** [comment]
If anyone's interested, adding `height: 0` to the flex item in the original example makes the child take the 100% as expected in both chrome and safari: http://jsfiddle.net/qegwrLu6/

```css
.flex-item {
  background-color: steelblue;
  -webkit-flex: 1 1 auto;
  flex: 1 1 auto;
  height: 0; /* <-- this helps */
}
```

**Comment by hk029** [comment]
change the `flex: auto` to `flex: 1` will solve this problem.
In fact, you can set `flex-basis` to any value except 'auto'  ,  according to CSS2.1 : 

> If the height of the containing block is not specified explicitly (i.e., it depends on content height), and this element is not absolutely positioned, the value computes to 'auto'. A percentage height on the root element is relative to the initial containing block.

**Comment by AlexWayfer** [comment]
> change the flex: auto to flex: 1 will solve this problem.

`1` makes the container height equal to item height in the issue-starter example. `0` (`flex: 1 1 0;`) resolves the problem.

**Comment by darthrevan** [comment]
@gsnedders thank you man saved my day!

**Comment by Wasimgit** [comment]
.flex-item {
    background-color: steelblue;
    flex-grow: 1;
    height: 0px; /* <--- right here! */
}

**Comment by ignatiusreza** [comment]
it still doesn't work when `.flex` have a `min-height` instead of a `height`.. :sob:

**Comment by coldKey1** [comment]
`.flex-child-item { margin: auto }` hope this helps

**Comment by lichristopher** [comment]
@ignatiusreza are you still having problem with it? because Im having that problem too

**Comment by ignatiusreza** [comment]
@lichristopher we end up restructuring the dom to avoid this specific issue..

**Comment by marcelombc** [comment]
If you are using `min-height` just add `height: 0` to the element with `min-height` and it should work.
Fiddle: http://jsfiddle.net/km8ezqup/

**Comment by OliverJAsh** [comment]
The test case at the top of this issue can be reduced slightly further to http://jsfiddle.net/OliverJAsh2/rx59Ljbw/2/.

``` css
.flex {
    height: 100px;
    display: flex;
    flex-direction: column;
}
.flex-item {
    background-color: steelblue;
    flex-grow: 1;
}
.element {
    height: 100%;
    background-color: orange;
}
```

Testing on latest browsers today, this works in Firefox and Chrome but fails in Safari.

Specifying `flex-basis: 0` or `height: 0` on the flex item (as suggested originally in https://github.com/philipwalton/flexbugs/issues/197#issuecomment-283211783) seems to workaround the issue in Safari.

Is this still considered a bug in Safari, or is Safari working according to spec? If Safari is working according to spec here, does this imply that other browsers (Firefox/Chrome) are actually the ones with a problem here (i.e. they shouldn't respect `height: 100%` unless the parent flex item has a `0` height/flex basis, like in Safari)?

**Comment by gsnedders** [comment]
@OliverJAsh The spec changed since I last quoted it in 2017, now saying:

>  If the flex container has a definite main size, a flex item’s post-flexing main size is treated as definite, even though it can rely on the indefinite sizes of any flex items in the same line. 

So the bug is once again Safari's.

That said, [this](https://wpt.fyi/results/css/css-flexbox/percentage-heights-003.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=percentage-heights-003) test for all this partly still fails in Edge(HTML) and Firefox because they always treat the flex item main size as definite even when the flex container has an indefinite main size.

**Comment by OliverJAsh** [comment]
@gsnedders Thanks for clarifying. In that case, do you know if there's an open bug filed with Safari, or do we need to open one?

**Comment by gsnedders** [comment]
Don't know off-hand.

**Comment by OliverJAsh** [comment]
I filed a bug here: https://bugs.webkit.org/show_bug.cgi?id=198375

**Comment by alexandar-mitsev** [comment]
@lichristopher we do have the same problem with min-height - https://jsfiddle.net/f1x9428q/5/
Works fine on Firefox, but brakes on Chrome. Could not locate a reported bug about it.

**Comment by vincent-ly** [comment]
`height:0` hack doesn't work on Chrome for iOS.

**Comment by ashokkumar360** [comment]
> http://jsfiddle.net/jonas8/w5jwxoL5/3/

"You save my life!"

**Comment by strarsis** [comment]
Try `min-height: inherit;` on the child element (works in recent Chrome)! 🚀

**Comment by bendman** [comment]
@strarsis Putting `min-height: inherit` on the flex item causes the flex item to be 100% the height of the flex container. This isn't always wanted; for example if it has siblings that also take up space.

Here is a more complete test case: https://jsfiddle.net/wLz0u27y/3/

**Comment by yfxie** [comment]
Add a flexbox again as a workaround.

```
.flexbox {
  display: flex;
  flex-direction: column;
}

.flex-item {
  flex: 1;
  display: flex;
  align-items: stretch; // To stretch the child height
}

.element-in-flex-item {
  // This item should be the same height to .flex-item
  // If you have margin: auto in the element, change it to margin: 0 auto;
}
```

**Comment by Kuohao-wu** [comment]
> Add a flexbox again as a workaround.
> 
> ```
> .flexbox {
>   display: flex;
>   flex-direction: column;
> }
> 
> .flex-item {
>   flex: 1;
>   display: flex;
>   align-items: stretch; // To stretch the child height
> }
> 
> .element-in-flex-item {
>   // This item should be the same height to .flex-item
>   // If you have margin: auto in the element, change it to margin: 0 auto;
> }
> ```

it work! thank you very much!
